# Generated by Django 4.1.1 on 2022-09-22 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_address", models.CharField(blank=True, max_length=400)),
                ("permenent_addresss", models.CharField(blank=True, max_length=400)),
                ("age", models.IntegerField(blank=True, null=True)),
                ("gender", models.CharField(blank=True, max_length=100)),
                ("dte_of_bir", models.DateField(blank=True, null=True)),
                ("blood_group", models.CharField(blank=True, max_length=100)),
                ("phone", models.CharField(blank=True, max_length=100)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CompanyDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("designation", models.CharField(blank=True, max_length=400)),
                ("experience", models.CharField(blank=True, max_length=400)),
                ("branch_code", models.CharField(blank=True, max_length=400)),
                ("project_manager", models.CharField(blank=True, max_length=400)),
                ("working_project", models.CharField(blank=True, max_length=400)),
                ("salary", models.FloatField(blank=True, null=True)),
                ("is_hr", models.BooleanField(default=False)),
                ("is_manager", models.BooleanField(default=False)),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="task3_app.profile",
                    ),
                ),
            ],
        ),
    ]
